# Generated by Django 4.2.1 on 2023-08-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapp', '0002_rename_valor_formulario2_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario1',
            name='moneda',
            field=models.CharField(max_length=100),
        ),
    ]
